from fastapi import FastAPI, Depends,HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from contextlib import asynccontextmanager
from typing import Optional,List
from schemas import CourseCreate,CourseResponse
from database import engine, Base, get_db
import models 
from schemas import CourseUpdate

# This tells FastAPI to create the database tables when the app starts
@asynccontextmanager
async def lifespan(app: FastAPI):
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    yield

app = FastAPI(title='Course Management API', version='1.0', lifespan=lifespan)

# ... (your existing @app.get('/') and @app.post('/api/courses/') routes stay the same for now)

@app.get("/")
def root():
    return {'message':'API running'}

# Make sure you have these imports at the top if they aren't there already:
# from fastapi import Depends
# from sqlalchemy.ext.asyncio import AsyncSession

@app.post('/api/courses/', response_model=CourseResponse)
# 1. Inject the database session using Depends()
async def create_course(course: CourseCreate, db: AsyncSession = Depends(get_db)):
    
    # 2. Convert Pydantic schema to an SQLAlchemy model instance
    # **course.model_dump() unpacks the dictionary into keyword arguments
    db_course = models.Course(**course.model_dump()) 
    
    # 3. Add to the session and commit asynchronously 
    db.add(db_course)
    await db.commit()
    
    # 4. Refresh to get the new ID generated by the database
    await db.refresh(db_course)
    
    # 5. Return the SQLAlchemy model (FastAPI will automatically convert it using CourseResponse)
    return db_course

@app.get('/api/courses/{course_id}', response_model=CourseResponse)
async def get_course(course_id: int, db: AsyncSession = Depends(get_db)):
    # Create the async query: SELECT * FROM courses WHERE id = course_id
    query = select(models.Course).where(models.Course.id == course_id)
    result = await db.execute(query)
    
    # .scalar_one_or_none() fetches the single record or returns None if missing
    course = result.scalar_one_or_none()
    
    # If the course doesn't exist, automatically raise a 404 error
    if course is None:
        raise HTTPException(status_code=404, detail="Course not found")
        
    return course

@app.get('/api/courses/', response_model=List[CourseResponse])
async def get_courses(
    skip: int = 0, 
    limit: int = 10, 
    department_id: Optional[int] = None, 
    db: AsyncSession = Depends(get_db)
):
    # Initialize the query: SELECT * FROM courses
    query = select(models.Course)
    
    # If a department_id query param is provided, filter by it
    if department_id is not None:
        query = query.where(models.Course.department_id == department_id)
        
    # Apply pagination offsets (skip) and constraints (limit)
    query = query.offset(skip).limit(limit)
    
    result = await db.execute(query)
    
    # .scalars().all() converts the results into a clean Python list of objects
    courses = result.scalars().all()
    return courses

@app.put('/api/courses/{course_id}', response_model=CourseResponse)
async def update_course(course_id: int, course_update: CourseUpdate, db: AsyncSession = Depends(get_db)):
    # 1. Find the existing course first
    query = select(models.Course).where(models.Course.id == course_id)
    result = await db.execute(query)
    db_course = result.scalar_one_or_none()
    
    if db_course is None:
        raise HTTPException(status_code=404, detail="Course not found")
        
    # 2. Extract only the fields the user actually wants to change
    # exclude_unset=True is Pydantic magic: it ignores fields the user didn't send!
    update_data = course_update.model_dump(exclude_unset=True)
    
    # 3. Apply the changes to our database object
    for key, value in update_data.items():
        setattr(db_course, key, value)
        
    # 4. Save and refresh
    await db.commit()
    await db.refresh(db_course)
    return db_course

@app.delete('/api/courses/{course_id}')
async def delete_course(course_id: int, db: AsyncSession = Depends(get_db)):
    # 1. Find the existing course
    query = select(models.Course).where(models.Course.id == course_id)
    result = await db.execute(query)
    db_course = result.scalar_one_or_none()
    
    if db_course is None:
        raise HTTPException(status_code=404, detail="Course not found")
        
    # 2. Delete it!
    await db.delete(db_course)
    await db.commit()
    
    return {"message": f"Course {course_id} deleted successfully"}